version: '3'

services:
        anonymizer:
                build:
                        context: ../
                        dockerfile: ./docker/Dockerfile
                image: docker.io/josejuanmartineziqvia/anonymizer:0.1
                ports:
                  - "9090:9090"
                container_name: anonymizer
                volumes:
                  - ../input:/opt/anonymizer/input
                  - ../output:/opt/anonymizer/output
